# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Josie Huang
name: Josie Huang

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar

#Specific contents
navbar-title: Josie Huang

#Navigation bar links
navbar-links:
- title: Home
  url: index.html
- title: CV
  url: /
- title: Publications
  url: publications.html
- title: Photos
  url: /
- title: ASH Labpage
  url: http://wilsonlab.la.psu.edu
- title: Novel Project
  url: novel.html
- title: Contact
  url: contact.html

#Introduction
intro_text: I am a second-year PhD student in Clinical Psychology at The Penn State University, State College. I am originally from China. Research-wise, I am currently working with <a href="http://psych.la.psu.edu/directory/sjw42">Dr. Stephen Wilson</a> on a project that examines the influences of contextual information on restrained eaters' neural reactivity to food and non-food reward cues. Our goal is to identify the neural markers that predict the motivational processes and food choices among individuals in obesogenic environment.<br/><br/>In my spare time, I enjoy running, reading, and writing my novel!

#Education
positions:
- degree: PhD candidate in Clinical Psychology
  year: 2017-present
  university: The Penn State University
  advisor: Dr. Stephen Wilson
  research: Contextual influences on reward processing in addiction.
- degree: M.A. (Psychology)
  year: 2014-2017
  university: San Diego State University
  advisor: Dr. Ksenija Marinkovic
  research: Neural correlates of cognitive and affective functions in binge drinkers.
- degree: B.S. (Psychology)
  year: 2008-2012
  university: Peking University
  advisor: Dr. Shihui Han
  research: The modulating effects of group membership on empathic neural responses.

#Program Skills
programskills:
- MATLAB
- R
- STATA
- Presentation
- E-Prime
- SPSS

#Neuroscience Skills
neuroskills:
- title: Fieldtrip (EEG & MEG)
  url: http://www.fieldtriptoolbox.org
- title: FSL (MRI)
  url: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki
- title: fMRIPrep
  url: http://fmriprep.readthedocs.io/en/latest/usage.html
 
# Publication List
publications:
- title: Huang. S., Holcomb, L. A., Cruz, S. M., & Marinkovic, K. (2018). Altered oscillatory brain dynamics of emotional processing in young binge drinkers. <i>Cognitive and Affective Behavioral Neuroscience, 18(1) </i>, 43-57. 
  url: https://link.springer.com/article/10.3758/s13415-017-0551-7
- title: Huang, S., Fan F., Zhang, Y., Yao, N., & Rodriguez, M. (2017). Attentional training for social anxiety in Chinese college students. <i> Chinese Journal of Clinical Psychology, 5 </i>, 986-990.
  url: /
- title: Huang & Han. (2014). Shared beliefs enhance shared feelings - Religious/irreligious identifications modulate empathic neural responses. <i> Social Neuroscience, 9(6)</i>, 639-649.
  url: https://www.tandfonline.com/doi/abs/10.1080/17470919.2014.934396
- title: Affan, R. O., Huang, S., Cruz, S. M., Holcomb, L. A., Nguyen, E., & Marinkovic, K. (2018). High-intensity binge drinking is associated with alterations in spontaneous neural oscillations in young adults. <i>Alcohol, 70</i>, 51-60.
  url: https://www.sciencedirect.com/science/article/pii/S0741832917308686
- title: Zhang, N., Fan, F., Huang, S., & Rodriguez, M. (2016). Mindfulness training for loneliness among Chinese college students - A pilot randomized controlled trial. <i>International Journal of Psychology</i>. 
  url: https://onlinelibrary.wiley.com/doi/abs/10.1002/ijop.12394
- title: Molnar, S. M., Beaton, L. E., Happer, J. P., Holcomb, L. A., Huang, S., Arienzo, D., & Marinkovic, K. (2018). Behavioral and brain activity indices of cognitive control deficits in binge drinkers. <i>Brain Sciences, 8(1), 9 </i>.
  url: http://www.mdpi.com/2076-3425/8/1/9

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

