# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Josie Huang
name: Josie Huang

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar

plugins:
  - jekyll-feed

#Specific contents
navbar-title: Josie Huang

#Navigation bar links
navbar-links:
- title: Home
  url: index.html
- title: CV
  url: /
 -title: Publications
  url: /
 -title: Photos
  url: /
 -title: ASH Labpage
  url: http://wilsonlab.la.psu.edu

#Introduction
intro_text: I am a second-year PhD student in Clinical Psychology at The Penn State University, State College.
					I am originally from China. Research-wise, I am currently working with <a href="http://psych.la.psu.edu/directory/sjw42">
					Dr. Stephen Wilson</a> on a project that examines the influences of contextual information on restrained 
					eaters' neural reactivity to food and non-food reward cues. Our goal is to identify the neural markers
					that predict the motivational processes and food choices among individuals in obesogenic environment.<br/><br/>
					In my spare time, I enjoy running, reading, and writing my novel!
          
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
theme: minima
theme: minima
